name: Clang tidy checks

on: [push]

jobs:
  check:
    name: Clang tidy Check 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        
      - name: "Install dependencies"
        run: |
          sudo apt-get install -y clang-10 clang-tidy-10 
      
      - name: "Install Boost from Source" 
        run: |
          cd ..
          git clone --depth 1 https://github.com/boostorg/boost.git --recursive --shallow-submodules
          cd boost
          ./bootstrap.sh 
          ./b2 headers
          sudo cp -r -L boost /usr/include
          rm -rf boost
      
      - name: "Run clang-tidy check"
        run: |
          clang-tidy-10 examples/tensor/*.cpp -- -Iinclude -std=c++17 > reports.txt

      - name: "Show clang tidy report"
        if: always()  
        run: |
          cat reports.txt
